name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Run tests
        run: go test -race -coverprofile=cover.out -covermode=atomic $(go list ./... | grep -v -E 'cmd$$')

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3